# Generated by Django 6.0.1 on 2026-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvCharging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
